### ISSUE TITLE
Run in different language

### ISSUE THREAD

**Issue by burakclk1** [aileftech/wikipedia-autovideo#5]
Default language is English, is it possible to run this for different languages, like Dutch, Turkish, German?

**Comment by aileftech** [comment]
It's definitely possible but results will be sub-par. You need to choose a language that's supported by AWS Polly, then change the code in `Polly.java` to select the correct voice for your language.

Also, you will need to change the references to the English Wikipedia. These are hardcoded so you'll need to change the code and recompile. These are the two most important things but I might be missing something else.

That said, I have generated 1 video in Dutch so it's definitely possible but it was a long time ago and now I can't remember all the exact steps; it will take you some trial and error.

**Comment by burakclk1** [comment]
Thanks for your comment. Could you please help me little bit? I did what you said. Now I'm getting this error

Exception in thread "main" java.lang.RuntimeException: Unsupported language: NL
        at com.autovideo.utils.Stopwords.isStopword(Stopwords.java:441)
        at com.autovideo.text.Summarizer.lambda$summarize$1(Summarizer.java:54)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.autovideo.text.Summarizer.lambda$summarize$2(Summarizer.java:53)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.autovideo.text.Summarizer.summarize(Summarizer.java:52)
        at com.autovideo.wiki.WikiSectionSplitter.lambda$split$0(WikiSectionSplitter.java:79)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.autovideo.wiki.WikiSectionSplitter.split(WikiSectionSplitter.java:77)
        at com.autovideo.wiki.WikiVideoCreator.createVideo(WikiVideoCreator.java:149)
        at com.autovideo.wiki.WikiVideoCreator.main(WikiVideoCreator.java:261)

**Comment by burakclk1** [comment]
@aileftech  I've solved the error what I got before. Now I'm stuck on this. I let search for Dutch "Voetbal" it means Football. But keep getting error can`t find image.


Starting video creation for Wikipedia page Voetbal and audio engine standard
http://nl.wikipedia.org/w/api.php?titles=Voetbal&format=json&explaintext=&continue=&action=query&prop=redirects%7Clanglinks%7Ccategories%7Clinks%7Cimages%7Crevisions%7Cextracts%7Cpageprops&rvprop=content&ppprop=wikibase_item&lllimit=500&pllimit=500&imlimit=500&rdlimit=500
Voetbal
Jul 27, 2022 11:13:24 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "set-cookie: WMF-Last-Access=27-Jul-2022;Path=/;HttpOnly;secure;Expires=Sun, 28 Aug 2022 12:00:00 GMT". Invalid 'expires' attribute: Sun, 28 Aug 2022 12:00:00 GMT
Jul 27, 2022 11:13:24 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "set-cookie: WMF-Last-Access-Global=27-Jul-2022;Path=/;Domain=.wikipedia.org;HttpOnly;secure;Expires=Sun, 28 Aug 2022 12:00:00 GMT". Invalid 'expires' attribute: Sun, 28 Aug 2022 12:00:00 GMT
[main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.0 sec].
Running: sh output/clean.sh
 OK!
Intro, Spelregels, Opstelling and Geschiedenis
        Intro   false
        Spelregels      false
        Opstelling      false
        Geschiedenis    false
        België  false
        Nederland       false
Section: Intro (801 chars)
Rendering audio: engine=Standard, ssml=false
Audio duration: 40
Section: Spelregels (1951 chars)
Rendering audio: engine=Standard, ssml=false
Audio duration: 105
[INFO] Video duration: 0
        2 images
                52.75 seconds each
        0 seconds video
        Total = 105.5
[ERROR] Error retrieving image: https://upload.wikimedia.org/wikipedia/commons/6/63//wiki/Bestand:Boisko.svg
[ERROR] Error retrieving image: https://upload.wikimedia.org/wikipedia/commons/e/e0//wiki/Bestand:Teamgeist_Ball_World_Cup_2006_Finale.jpg
Section: Opstelling (1613 chars)
Rendering audio: engine=Standard, ssml=false
Audio duration: 89
Section: Geschiedenis (449 chars)
Rendering audio: engine=Standard, ssml=false
Audio duration: 24
Section: België (353 chars)
Rendering audio: engine=Standard, ssml=false
Audio duration: 21
Section: Nederland (913 chars)
Rendering audio: engine=Standard, ssml=false
Audio duration: 52
[INFO] Video duration: 0
        1 images
                52.25 seconds each
        0 seconds video
        Total = 52.25
[ERROR] Error retrieving image: https://upload.wikimedia.org/wikipedia/commons/3/3a//wiki/Bestand:Voetbalwedstrijd_Nederland_-_België_(1-0).ogv
Exception in thread "main" org.apache.http.client.HttpResponseException: status code: 404, reason phrase: Not Found
        at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:70)
        at org.apache.http.client.fluent.Response.handleResponse(Response.java:90)
        at org.apache.http.client.fluent.Response.returnContent(Response.java:97)
        at com.autovideo.wiki.WikiVideoCreator.createVideo(WikiVideoCreator.java:221)
        at com.autovideo.wiki.WikiVideoCreator.main(WikiVideoCreator.java:261)

**Comment by aileftech** [comment]
It seems that for whatever reason the tool extracted a wrong URL for the image. 

If you check [https://upload.wikimedia.org/wikipedia/commons/3/3a//wiki/Bestand:Voetbalwedstrijd_Nederland_-_België_(1-0).ogv](https://upload.wikimedia.org/wikipedia/commons/3/3a//wiki/Bestand:Voetbalwedstrijd_Nederland_-_Belgi%C3%AB_(1-0).ogv) it actually is a 404 error.

Can't really tell why this happened, though. It must be something specific for this page: do you get the same error for every page in Dutch?

In any case, you will have to either properly debug the reason why the URL is incorrect or implement a solution that skips the 404 images instead of stopping the execution of the program.
