### ISSUE TITLE
sh gen_video.sh -- Error initializing filter 'fade' with args 't=out:st=-0.25:d=1'

### ISSUE THREAD

**Issue by Thrqureshi** [aileftech/wikipedia-autovideo#6]
Hi there

I am getting the following error when running the script. 

Running: sh gen_video.sh
ffmpeg version N-107585-g665349c4c0-20220730 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220730
  libavutil      57. 30.100 / 57. 30.100
  libavcodec     59. 40.100 / 59. 40.100
  libavformat    59. 29.100 / 59. 29.100
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 46.101 /  8. 46.101
  libswscale      6.  8.101 /  6.  8.101
  libswresample   4.  8.100 /  4.  8.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, image2, from 'tmp/1.jpg':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 80128 kb/s
  Stream #0:0: Video: mjpeg (Progressive), yuvj420p(pc, bt470bg/unknown/unknown), 1280x853 [SAR 1:1 DAR 1280:853], 25 fps, 25 tbr, 25 tbn
Input #1, image2, from 'tmp/2.jpg':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 56823 kb/s
  Stream #1:0: Video: mjpeg (Progressive), yuvj420p(pc, bt470bg/unknown/unknown), 1280x853 [SAR 1:1 DAR 1280:853], 25 fps, 25 tbr, 25 tbn
[mp3 @ 000002026c00d980] Estimating duration from bitrate, this may be inaccurate
Input #2, mp3, from 'audio.mp3':
  Metadata:
    encoder         : Lavf58.76.100
  Duration: 00:00:16.67, start: 0.000000, bitrate: 48 kb/s
  Stream #2:0: Audio: mp3, 22050 Hz, mono, fltp, 48 kb/s
Input #3, mov,mp4,m4a,3gp,3g2,mj2, from 'tmp/0.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomavc1
    creation_time   : 2015-11-26T21:39:45.000000Z
  Duration: 00:00:15.00, start: 0.000000, bitrate: 4516 kb/s
  Stream #3:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 4512 kb/s, 30 fps, 30 tbr, 30 tbn (default)
    Metadata:
      creation_time   : 2015-11-26T21:39:45.000000Z
      handler_name    : L-SMASH Video Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
[fade @ 000002026cb9ae00] Value -0.250000 for parameter 'st' out of range [0 - 9.22337e+12]
[fade @ 000002026cb9ae00] Error setting option st to value -0.25.
[Parsed_fade_4 @ 000002026cb9ad00] Error applying options to the filter.
[AVFilterGraph @ 000002026cab4880] Error initializing filter 'fade' with args 't=out:st=-0.25:d=1'
Error initializing complex filters.
Result too large
 ERROR!
Exception in thread "main" java.lang.RuntimeException: Error executing sh script
        at com.autovideo.utils.ProcessRunner.run(ProcessRunner.java:32)
        at com.autovideo.video.VideoRenderer.createVideo(VideoRenderer.java:315)
        at com.autovideo.video.VideoRenderer.render(VideoRenderer.java:65)
        at com.autovideo.wiki.WikiVideoCreator.createVideo(WikiVideoCreator.java:219)
        at com.autovideo.wiki.WikiVideoCreator.main(WikiVideoCreator.java:261)

**Comment by aileftech** [comment]
```
[fade @ 000002026cb9ae00] Value -0.250000 for parameter 'st' out of range [0 - 9.22337e+12]
```

It seems the generated script `gen_video.sh` contains an invalid value for the `st` param. Not sure why, I never got this error before. But it should be easy to fix: you need to find the place in the code where this value is set, and just put `0` if the value is negative instead.

I'm not actively maintaining this project so you'll have to implement it yourself. If you do, though, you can create a PR so I can merge it into the repo, if you'd like.

**Comment by Thrqureshi** [comment]
Thank for your reply

I did change the value to 0 in two occasions in gen_video script but it is
taking extremely long time to create a video. I was trying to create a new
York video as sample. I have to cancel the script after 4 hours of
continuous working

How much time does it normally take to create a video

**Comment by aileftech** [comment]
It usually took about 20-30 minutes, maybe longer if the page was big but in my experience it never reached more than 1 hour. Was it stuck or still printing the ffmpeg output?

**Comment by Thrqureshi** [comment]
Still printing like this after changing the value of st=0

[swscaler @ 0000022ba501bb40] deprecated pixel format used, make sure you
did set range correctly


*Frame rate very high for a muxer not efficiently supporting it.Please
consider specifying a lower framerate, a different muxer or setting
vsync/fps_mode to vfr[*libx264 @ 0000022b9c17b400] using SAR=1/1
[libx264 @ 0000022b9c17b400] *MB rate (8160000000) > level limit (16711680)*
[libx264 @ 0000022b9c17b400] using cpu capabilities: MMX2 SSE2Fast SSSE3
SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0000022b9c17b400] profile High, level 6.2, 4:2:0, 8-bit
[libx264 @ 0000022b9c17b400] 264 - core 164 - H.264/MPEG-4 AVC codec -
Copyleft 2003-2022 - http://www.videolan.org/x264.html - options: cabac=1
ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00
mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11
fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2
sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0
constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1
weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40
intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0
qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'output/video.final.0.mp4':
  Metadata:
    encoder         : Lavf59.29.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive),
1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 1000k tbn
    Metadata:
      encoder         : Lavc59.40.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 22050 Hz, mono, fltp,
69 kb/s
    Metadata:
      encoder         : Lavc59.40.100 aac
[swscaler @ 0000022bae561cc0] *deprecated pixel format used, make sure you
did set range correctly*
More than 1000 frames duplicated
[swscaler @ 0000022bdd668040] *deprecated pixel format used, make sure you
did set range correctly*0 speed=0.000185x
More than 10000 frames duplicated
[swscaler @ 0000022be06e2140] *deprecated pixel format used, make sure you
did set range correctly*0 speed=0.000139x
More than 100000 frames duplicated
frame=119944 fps=136 q=33.0 size=       0kB time=00:00:00.11 bitrate=
3.2kbits/s *dup=119996* drop=0 speed=0.000136x
[swscaler @ 0000022be06d20c0] *deprecated pixel format used, make sure you
did set range correctly*
frame=159944 fps=135 q=33.0 size=    8192kB time=00:00:00.15
bitrate=419587.5kbits/s *dup=159995* drop=0 speed=0.000135x
[swscaler @ 0000022be4ff8a80] *deprecated pixel format used, make sure you
did set range correctly*

**Comment by aileftech** [comment]
Yeah, that's normal ffmpeg output. 

frame=159944 fps=135 q=33.0 size=    8192kB **time=00:00:00.15**

The "time" shows how much it has rendered up until now, not sure why it's taking that long though. Could it be that your machine is particularly slow?

speed=0.000135x

Your speed is particularly low, but this definitely is not normal in my experience.

**Comment by aileftech** [comment]
I'm closing this issue as the original `st < 0` problem seems solved and the speed is something that's specific to your machine (it relates to ffmpeg, so it's out of our control).
